# minimum access control level。[private | fileprivate | internal | public | open]
# ここで指定したレベル以上がドキュメント化される
min_acl: public
 
#実行前に出力先フォルダをクリーン
clean: true
 
# 著者
author: PAYJP
 
# 著者のURL
author_url: https://github.com/payjp
 
# ドキュメント化するモジュールの名前
module: PAYJP
