
min_acl: public
clean: true
author: PAYJP
author_url: https://pay.jp
github_url: https://github.com/payjp/payjp-ios
module: PAYJP
hide_documentation_coverage: true
copyright: "&copy; 2020 [PAY.JP](https://pay.jp) All rights reserved."