language: objective-c
matrix:
  include:
    - osx_image: xcode10

before_install:
  - brew update
  - brew unlink carthage
  - brew install carthage
  - carthage bootstrap --no-use-binaries --platform ios

script:
    - xcodebuild -scheme PAYJP -sdk iphonesimulator -destination 'platform=iOS Simulator,id=1AEF6BFF-F0C8-4A2D-ACEA-E85C97D21628,OS=12.0' -configuration Debug test | xcpretty -c

cache:
  directories:
    - Carthage